Workflow Files for NextJS project
IIITians-Network-23/IIITiansNetwork pull request #37
Opened 2024-01-06 18:29 UTC by zakhaev26

Added configs for Checking Build status of the Project.
Related to #36.

2024-01-06 18:34 UTC, zakhaev26 commented
@DhairyaMajmudar review please

2024-01-06 20:20 UTC, DhairyaMajmudar requested changes

2024-01-06 20:20 UTC, DhairyaMajmudar commented on package.json
> +    "lint": "next lint "
pls. remove extra spaces

2024-01-06 20:39 UTC, zakhaev26 commented on package.json
> +    "lint": "next lint "
done

2024-01-08 20:18 UTC, yogeyyy approved these changes

2024-01-09 19:03 UTC, yogeyyy approved these changes

2024-01-09 19:04 UTC, merged